# docker-compose.yml
version: '3.3'

services:
  chatgpt-web:
    build: ./ # dockerfile所在目录
    environment:
      TZ: Asia/Shanghai
      APIKEY: "your api key" #APIKEY
      APIURL: "" #自定义API接口
      MODEL: "gpt-3.5-turbo-0301" #模型
      BOT_DESC: "你是一个AI助手,我需要你模拟一名温柔贴心的女朋友来回答我的问题." #ai设定
      MAX_TOKENS: 512
      TEMPREATURE: 0.9
      TOP_P: 1
      FREQ: 0.0
      PROXY: "http://host.docker.internal:10809" #代理地址
      AUTH_USER: "" #认证用户
      AUTH_PASSWORD: "" #认证密码
    restart: always
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
